'use strict';
const GENS = [
  {id:'script', nome:'script.sh',           desc:'Script de automação que minera sozinho',                  base:15,     prod:0.1,    tag:'>_'},
  {id:'cpu',    nome:'CPU usada',           desc:'Xeon de leilão rodando no talo',                          base:100,    prod:1,      tag:'CPU'},
  {id:'gpu',    nome:'GPU de mineração',    desc:'Meio torrada, mas ainda hasheia',                         base:1100,   prod:8,      tag:'GPU'},
  {id:'ssd',    nome:'Farm de SSD',         desc:'Plota dados a noite inteira',                             base:12000,  prod:47,     tag:'SSD'},
  {id:'srv',    nome:'Servidor torre',      desc:'Barulho de turbina, lucro de banco',                      base:130000, prod:260,    tag:'SRV'},
  {id:'rack',   nome:'Rack de servidores',  desc:'Sua conta de luz chora',                                  base:1.4e6,  prod:1400,   tag:'RCK'},
  {id:'bot',    nome:'Botnet',              desc:'Geladeiras inteligentes do mundo todo trabalham pra você',base:2e7,    prod:7800,   tag:'BOT'},
  {id:'dtc',    nome:'Datacenter',          desc:'Você É a nuvem agora',                                    base:3.3e8,  prod:44000,  tag:'DTC'},
  {id:'qtm',    nome:'Computador quântico', desc:'Quebra RSA no café da manhã',                             base:5.1e9,  prod:260000, tag:'QBT'},
];
const UPG = [
  {id:'mouse',   nome:'Switches mecânicos',   desc:'Poder de clique ×2',                 custo:100,    tipo:'clickMult', val:2,   req:s=>s.clicks>=5},
  {id:'oc_scr',  nome:'Overclock nos scripts',desc:'script.sh produz ×2',                custo:500,    tipo:'genMult', gen:'script', val:2, req:s=>g('script')>=5},
  {id:'teclado', nome:'Teclado mecânico',     desc:'Poder de clique ×2',                 custo:1200,   tipo:'clickMult', val:2,   req:s=>s.upg.includes('mouse')},
  {id:'pasta',   nome:'Pasta térmica premium',desc:'CPUs produzem ×2',                   custo:5000,   tipo:'genMult', gen:'cpu', val:2, req:s=>g('cpu')>=5},
  {id:'macro1',  nome:'Macro básico',         desc:'Clique ganha +1% do seu bits/s',     custo:8000,   tipo:'clickPct', val:0.01, req:s=>s.clicks>=75},
  {id:'cafe',    nome:'Café infinito',        desc:'Toda produção +10%',                  custo:10000,  tipo:'allMult', val:1.1, req:s=>s.total>=5000},
  {id:'monitor', nome:'Monitor curvo extra',  desc:'Poder de clique ×2',                 custo:25000,  tipo:'clickMult', val:2,   req:s=>s.upg.includes('teclado')},
  {id:'drivers', nome:'Drivers hackeados',    desc:'GPUs produzem ×2',                   custo:50000,  tipo:'genMult', gen:'gpu', val:2, req:s=>g('gpu')>=5},
  {id:'dedo',    nome:'Dedo biônico',         desc:'Chance de crítico 5% → 15%',         custo:120000, tipo:'crit', val:0.15, req:s=>s.clicks>=400},
  {id:'macro2',  nome:'Macro avançado',       desc:'Clique ganha +4% do seu bits/s',     custo:150000, tipo:'clickPct', val:0.04, req:s=>s.upg.includes('macro1')},
  {id:'raid',    nome:'RAID 0 sem medo',      desc:'Farms de SSD produzem ×2',           custo:400000, tipo:'genMult', gen:'ssd', val:2, req:s=>g('ssd')>=5},
  {id:'luvas',   nome:'Luvas de fibra ótica', desc:'Poder de clique ×3',                 custo:1e6,    tipo:'clickMult', val:3,   req:s=>s.upg.includes('monitor')},
  {id:'water',   nome:'Refrigeração líquida', desc:'Servidores produzem ×2',             custo:3e6,    tipo:'genMult', gen:'srv', val:2, req:s=>g('srv')>=5},
  {id:'fibra',   nome:'Fibra ótica dedicada', desc:'Racks produzem ×2',                  custo:2.5e7,  tipo:'genMult', gen:'rack', val:2, req:s=>g('rack')>=5},
  {id:'neural',  nome:'Implante neural',      desc:'Poder de clique ×5',                 custo:5e7,    tipo:'clickMult', val:5,   req:s=>s.upg.includes('luvas')},
  {id:'worm',    nome:'Worm polimórfico',     desc:'Botnets produzem ×2',                custo:1.5e8,  tipo:'genMult', gen:'bot', val:2, req:s=>g('bot')>=5},
  {id:'ia',      nome:'IA otimizadora',       desc:'Toda produção ×2',                   custo:2e9,    tipo:'allMult', val:2,   req:s=>g('dtc')>=1},
  {id:'ram',     nome:'RAM no talo',          desc:'script.sh produz ×3',                custo:30000,  tipo:'genMult', gen:'script', val:3, req:s=>g('script')>=15},
  {id:'arctic',  nome:'Ventilador na janela', desc:'CPUs produzem ×3',                   custo:120000, tipo:'genMult', gen:'cpu', val:3, req:s=>g('cpu')>=10},
  {id:'vbios',   nome:'vBIOS desbloqueada',   desc:'GPUs produzem ×3',                   custo:8e5,    tipo:'genMult', gen:'gpu', val:3, req:s=>g('gpu')>=10},
  /* escritório (loc 1) */
  {loc:1, id:'estagiario', nome:'Estagiário de TI',         desc:'Toda produção +30%',           custo:3e9,   tipo:'allMult', val:1.3, req:s=>true},
  {loc:1, id:'cafeteira',  nome:'Cafeteira industrial',     desc:'Poder de clique ×5',           custo:6e9,   tipo:'clickMult', val:5, req:s=>true},
  {loc:1, id:'devops',     nome:'Time DevOps terceirizado', desc:'script.sh produz ×10',         custo:1.2e10,tipo:'genMult', gen:'script', val:10, req:s=>g('script')>=25},
  {loc:1, id:'cadeira',    nome:'Cadeira ergonômica de 8k', desc:'Poder de clique ×4',           custo:2.5e10,tipo:'clickMult', val:4, req:s=>s.upg.includes('cafeteira')},
  {loc:1, id:'arcond',     nome:'Ar-condicionado central',  desc:'Servidores produzem ×4',       custo:5e10,  tipo:'genMult', gen:'srv', val:4, req:s=>g('srv')>=10},
  {loc:1, id:'kvm',        nome:'Switch KVM 8 portas',      desc:'Chance de crítico 15% → 20%',  custo:8e10,  tipo:'crit', val:0.2, req:s=>s.clicks>=1500},
  {loc:1, id:'ultrawide',  nome:'Ultrawide 49 polegadas',   desc:'Clique ganha +6% do bits/s',   custo:1.5e11,tipo:'clickPct', val:0.06, req:s=>s.upg.includes('macro2')},
  {loc:1, id:'linkded',    nome:'Link dedicado 10Gbps',     desc:'Racks produzem ×4',            custo:2.5e11,tipo:'genMult', gen:'rack', val:4, req:s=>g('rack')>=10},
  {loc:1, id:'noc',        nome:'NOC 24/7',                 desc:'Botnets produzem ×4',          custo:4e11,  tipo:'genMult', gen:'bot', val:4, req:s=>g('bot')>=10},
  {loc:1, id:'gerador',    nome:'Gerador a diesel',         desc:'Datacenters produzem ×4',      custo:6e11,  tipo:'genMult', gen:'dtc', val:4, req:s=>g('dtc')>=5},
  {loc:1, id:'reuniao',    nome:'Sala de reunião (vazia)',  desc:'Toda produção +50%',           custo:8e11,  tipo:'allMult', val:1.5, req:s=>s.upg.length>=22},
  {loc:1, id:'fortinet',   nome:'Firewall de enfeite',      desc:'Toda produção ×2',             custo:1.2e12,tipo:'allMult', val:2, req:s=>s.total>=5e11},
  /* NASA (loc 2) */
  {loc:2, id:'cracha',     nome:'Crachá de "visitante"',     desc:'Toda produção +50%',          custo:1.2e13, tipo:'allMult', val:1.5, req:s=>true},
  {loc:2, id:'luvastro',   nome:'Luvas de astronauta',       desc:'Poder de clique ×8',          custo:2.5e13, tipo:'clickMult', val:8, req:s=>true},
  {loc:2, id:'apollo',     nome:'Mainframe da Apollo 11',    desc:'CPUs produzem ×20',           custo:5e13,   tipo:'genMult', gen:'cpu', val:20, req:s=>g('cpu')>=25},
  {loc:2, id:'cafelio',    nome:'Café liofilizado',          desc:'Toda produção +50%',          custo:9e13,   tipo:'allMult', val:1.5, req:s=>s.upg.includes('cracha')},
  {loc:2, id:'antena',     nome:'Antena de espaço profundo', desc:'Botnets produzem ×8',         custo:1.8e14, tipo:'genMult', gen:'bot', val:8, req:s=>g('bot')>=15},
  {loc:2, id:'telescopio', nome:'Telescópio "emprestado"',   desc:'Chance de crítico 20% → 25%', custo:3e14,   tipo:'crit', val:0.25, req:s=>s.clicks>=4000},
  {loc:2, id:'satlink',    nome:'Uplink de satélite',        desc:'Clique ganha +10% do bits/s', custo:5e14,   tipo:'clickPct', val:0.10, req:s=>s.upg.includes('ultrawide')},
  {loc:2, id:'criogenia',  nome:'Refrigeração criogênica',   desc:'Computadores quânticos ×5',   custo:8e14,   tipo:'genMult', gen:'qtm', val:5, req:s=>g('qtm')>=5},
  {loc:2, id:'enxame',     nome:'Enxame de microssatélites', desc:'Racks produzem ×8',           custo:1.2e15, tipo:'genMult', gen:'rack', val:8, req:s=>g('rack')>=15},
  {loc:2, id:'foguete',    nome:'Combustível de foguete',    desc:'Datacenters produzem ×8',     custo:2e15,   tipo:'genMult', gen:'dtc', val:8, req:s=>g('dtc')>=10},
  {loc:2, id:'missao',     nome:'Controle da missão',        desc:'Toda produção ×2',            custo:3e15,   tipo:'allMult', val:2, req:s=>s.upg.length>=32},
  {loc:2, id:'marte',      nome:'Rover de Marte minerando',  desc:'Toda produção ×2',            custo:5e15,   tipo:'allMult', val:2, req:s=>s.total>=2e15},
  /* Casa Branca (loc 3) */
  {loc:3, id:'crachaoval', nome:'Crachá da ala oeste',         desc:'Toda produção ×2',            custo:6e16,  tipo:'allMult', val:2, req:s=>true},
  {loc:3, id:'orcamento',  nome:'Orçamento "confidencial"',    desc:'Poder de clique ×15',         custo:1.2e17,tipo:'clickMult', val:15, req:s=>true},
  {loc:3, id:'nsa',        nome:'Backdoor da NSA',             desc:'Botnets produzem ×15',        custo:2.5e17,tipo:'genMult', gen:'bot', val:15, req:s=>g('bot')>=25},
  {loc:3, id:'redfone',    nome:'Grampo no telefone vermelho', desc:'Clique ganha +20% do bits/s', custo:4e17,  tipo:'clickPct', val:0.20, req:s=>s.upg.includes('satlink')},
  {loc:3, id:'bunker',     nome:'Datacenter no bunker',        desc:'Datacenters produzem ×15',    custo:7e17,  tipo:'genMult', gen:'dtc', val:15, req:s=>g('dtc')>=15},
  {loc:3, id:'pentagono',  nome:'Quântico do Pentágono',       desc:'Computadores quânticos ×10',  custo:1.2e18,tipo:'genMult', gen:'qtm', val:10, req:s=>g('qtm')>=10},
  {loc:3, id:'botao',      nome:'Botão vermelho (não aperte)', desc:'Chance de crítico 25% → 35%', custo:2e18,  tipo:'crit', val:0.35, req:s=>s.clicks>=8000},
  {loc:3, id:'lobista',    nome:'Lobista em tempo integral',   desc:'Toda produção ×2',            custo:3e18,  tipo:'allMult', val:2, req:s=>s.upg.length>=42},
  {loc:3, id:'execorder',  nome:'Ordem executiva 1337',        desc:'Toda produção ×3',            custo:5e18,  tipo:'allMult', val:3, req:s=>s.upg.includes('crachaoval')},
  {loc:3, id:'af1',        nome:'Starlink no Air Force One',   desc:'Servidores produzem ×20',     custo:7e18,  tipo:'genMult', gen:'srv', val:20, req:s=>g('srv')>=25},
  {loc:3, id:'deepstate',  nome:'Estado profundo',             desc:'script.sh produz ×100',       custo:9e18,  tipo:'genMult', gen:'script', val:100, req:s=>g('script')>=50},
  {loc:3, id:'imunidade',  nome:'Imunidade diplomática',       desc:'Toda produção ×5',            custo:2e19,  tipo:'allMult', val:5, req:s=>s.total>=1e19},
];
const LOCAIS = [
  {id:'quarto',     nome:'seu quarto',              prompt:'root@h4ckfarm:~$',       mult:1,
   wall:'#071009', floor:'#0a1410', grid:'#0c1f15'},
  {id:'escritorio', nome:'escritório',              prompt:'root@startup:~$',        mult:4,   custo:2e9,
   req:s=>s.total>=5e8,
   desc:'saia do quarto: escritório de verdade. novos upgrades + toda produção ×4',
   flavor:'você saiu do quarto. CNPJ de fachada, ar-condicionado e upgrades corporativos liberados.',
   wall:'#0a1016', floor:'#0c1320', grid:'#13243a'},
  {id:'nasa',       nome:'NASA — sala de controle', prompt:'root@nasa.gov:~#',       mult:20,  custo:5e12,
   req:s=>s.total>=1e12,
   desc:'"consultoria" na NASA. novos upgrades + toda produção ×20',
   flavor:'a NASA "contratou" você. sala de controle inteira e upgrades espaciais liberados.',
   wall:'#06101e', floor:'#081628', grid:'#11294a'},
  {id:'casabranca', nome:'Casa Branca — sala de crise', prompt:'root@whitehouse.gov:~#', mult:100, custo:1e16,
   req:s=>s.total>=2e15,
   desc:'o topo da cadeia. novos upgrades + toda produção ×100',
   flavor:'ninguém sabe como você chegou na sala de crise. upgrades presidenciais liberados.',
   wall:'#141008', floor:'#181206', grid:'#2e2410'},
];
const RANKS = [
  [0,'n00b'],[1e3,'lammer'],[1e4,'script kiddie'],[1e5,'defacer'],
  [1e6,'cracker'],[1e7,'hacker'],[1e8,'h4x0r de elite'],
  [1e9,'fantasma cibernético'],[1e10,'lenda da deep web'],[1e11,'deus do mainframe'],
];
const ACH = [
  {id:'c1',       nome:'Hello, World',          desc:'Execute seu primeiro comando',          cond:s=>s.clicks>=1},
  {id:'c100',     nome:'Dedo nervoso',           desc:'50 comandos executados',               cond:s=>s.clicks>=50},
  {id:'c1k',      nome:'LER chegando',           desc:'500 comandos executados',              cond:s=>s.clicks>=500},
  {id:'c10k',     nome:'Túnel do carpo',         desc:'2.500 comandos executados',            cond:s=>s.clicks>=2500},
  {id:'g1',       nome:'Automatizado',           desc:'Compre seu primeiro script.sh',        cond:s=>g('script')>=1},
  {id:'g10',      nome:'DevOps raiz',            desc:'Tenha 10 script.sh',                   cond:s=>g('script')>=10},
  {id:'cpu1',     nome:'Silício quente',         desc:'Compre uma CPU',                       cond:s=>g('cpu')>=1},
  {id:'gpu1',     nome:'Cooler de avião',        desc:'Compre uma GPU',                       cond:s=>g('gpu')>=1},
  {id:'srv1',     nome:'Sysadmin',               desc:'Compre um servidor',                   cond:s=>g('srv')>=1},
  {id:'bot1',     nome:'Mestre das marionetes',  desc:'Monte uma botnet',                     cond:s=>g('bot')>=1},
  {id:'qtm1',     nome:'Gato de Schrödinger',    desc:'Compre um computador quântico',        cond:s=>g('qtm')>=1},
  {id:'t1k',      nome:'Primeiro caixa',         desc:'Minere 1K bits no total',              cond:s=>s.total>=1e3},
  {id:'t1m',      nome:'Milionário digital',     desc:'Minere 1M bits no total',              cond:s=>s.total>=1e6},
  {id:'t1b',      nome:'Bilionário das sombras', desc:'Minere 1B bits no total',              cond:s=>s.total>=1e9},
  {id:'u5',       nome:'Setup evoluindo',        desc:'Compre 5 upgrades',                    cond:s=>s.upg.length>=5},
  {id:'u15',      nome:'Setup dos sonhos',       desc:'Compre 15 upgrades',                   cond:s=>s.upg.length>=15},
  {id:'b100',     nome:'Renda passiva',          desc:'Alcance 100 bits/s',                   cond:()=>bps>=100},
  {id:'b10k',     nome:'Impressora de bits',     desc:'Alcance 10K bits/s',                   cond:()=>bps>=1e4},
  {id:'b1m',      nome:'Singularidade',          desc:'Alcance 1M bits/s',                    cond:()=>bps>=1e6},
  {id:'gold1',    nome:'Pacote interceptado',    desc:'Clique em um pacote de dados dourado', cond:s=>s.goldClicks>=1},
  {id:'gold10',   nome:'Sniffer profissional',   desc:'Intercepte 10 pacotes dourados',       cond:s=>s.goldClicks>=10},
  {id:'ttt1',     nome:'Velha hackeada',         desc:'Vença a IA de defesa no jogo da velha',cond:s=>s.ttt.wins>=1},
  {id:'ttt3',     nome:'IA humilhada',           desc:'Vença 3 duelos contra a IA de defesa', cond:s=>s.ttt.wins>=3},
  {id:'ms3',      nome:'Operador de contratos',  desc:'Complete 3 missões',                   cond:s=>s.missionIdx>=3},
  {id:'msall',    nome:'Currículo criminoso',    desc:'Complete todas as missões',             cond:s=>s.missionIdx>=MISSOES.length},
  {id:'u30',      nome:'Acumulador compulsivo',  desc:'Compre 30 upgrades',                   cond:s=>s.upg.length>=30},
  {id:'loc1',     nome:'Saiu do quarto',         desc:'Mude-se pro escritório',               cond:s=>s.loc>=1},
  {id:'loc2',     nome:'Foguete não tem ré',     desc:'Assuma a sala de controle da NASA',    cond:s=>s.loc>=2},
  {id:'loc3',     nome:'Acima da lei',           desc:'Opere da Casa Branca',                 cond:s=>s.loc>=3},
  {id:'prestige1',nome:'Kernel Panic',           desc:'Execute seu primeiro prestige',        cond:s=>(s.prestige||0)>=1},
  {id:'prestige5',nome:'Veterano do Submundo',   desc:'Execute 5 prestiges',                  cond:s=>(s.prestige||0)>=5},
];
const MISSOES = [
  {id:'m1',  nome:'Aquecendo os dedos',    desc:'Execute 15 comandos no terminal',
   prog:s=>[s.clicks,15],
   evento:'seus comandos chamaram atenção: um corretor da deep web comprou seus logs de sessão',
   rew:()=>Math.max(100, bps*30+clickPow*60)},
  {id:'m2',  nome:'Automatize ou morra',   desc:'Tenha 3 script.sh minerando por você',
   prog:s=>[g('script'),3],
   evento:'um dos seus scripts achou uma carteira esquecida num FTP aberto',
   rew:()=>Math.max(250, bps*40+clickPow*80)},
  {id:'m3',  nome:'Força bruta literal',   desc:'Tenha 2 CPUs usadas no talo',
   prog:s=>[g('cpu'),2],
   evento:'suas CPUs quebraram um hash valioso por pura força bruta',
   rew:()=>Math.max(600, bps*45+clickPow*100)},
  {id:'m4',  nome:'Flow state',            desc:'Encadeie 5 comandos no mesmo evento',
   prog:s=>[s.bestCombo,5],
   evento:'no flow absoluto, você fechou um contrato relâmpago de pentest',
   rew:()=>Math.max(900, bps*50+clickPow*150)},
  {id:'m5',  nome:'Fazendinha de GPU',     desc:'Tenha 3 GPUs de mineração',
   prog:s=>[g('gpu'),3],
   evento:'sua farm de GPU minerou um bloco raro de madrugada',
   rew:()=>Math.max(3000, bps*60+clickPow*200)},
  {id:'m6',  nome:'Sniffer de elite',      desc:'Intercepte 3 pacotes de dados dourados',
   prog:s=>[s.goldClicks,3],
   evento:'os pacotes interceptados tinham credenciais de um banco offshore',
   rew:()=>Math.max(6000, bps*90+clickPow*250)},
  {id:'m7',  nome:'Setup decente',         desc:'Instale 4 upgrades no seu setup',
   prog:s=>[s.upg.length,4],
   evento:'com o setup novo, o mercado negro liberou um contrato premium',
   buffMult:2, buffSecs:120},
  {id:'m8',  nome:'Acumulador de dados',   desc:'Tenha 2 farms de SSD plotando',
   prog:s=>[g('ssd'),2],
   evento:'seus SSDs guardavam um dump que foi a leilão na deep web',
   rew:()=>Math.max(25000, bps*90+clickPow*300)},
  {id:'m9',  nome:'Mãos de aço',           desc:'Execute 300 comandos no terminal',
   prog:s=>[s.clicks,300],
   evento:'300 comandos depois, sua reputação atraiu um cliente anônimo generoso',
   rew:()=>Math.max(40000, bps*120+clickPow*400)},
  {id:'m10', nome:'Sala de máquinas',      desc:'Tenha 2 servidores torre roncando',
   prog:s=>[g('srv'),2],
   evento:'seu servidor hospedou um site "questionável" por uma noite — pagamento adiantado',
   rew:()=>Math.max(250000, bps*120+clickPow*500)},
  {id:'m11', nome:'Exército de geladeiras',desc:'Monte uma botnet',
   prog:s=>[g('bot'),1],
   evento:'sua botnet foi alugada pra um "teste de estresse" muito bem pago',
   buffMult:3, buffSecs:90},
  {id:'m12', nome:'Você é a nuvem',        desc:'Compre um datacenter',
   prog:s=>[g('dtc'),1],
   evento:'seu datacenter fechou contrato de hospedagem discreta com meio submundo',
   rew:()=>Math.max(5e7, bps*180+clickPow*1000)},
];
const CMDS = [
  {c:'ls',                                           m:1,   out:['exploits/  wallet.dat  botnet.sh']},
  {c:'top',                                          m:1,   out:['CPU {n}% — minerador comendo tudo']},
  {c:'clear',                                        m:1,   out:['terminal limpo. evidências? nunca vi']},
  {c:'pwd',                                          m:1,   out:['/root/h4ckfarm']},
  {c:'whoami',                                       m:1,   out:['root (obviamente)']},
  {c:'ls -la',                                       m:1,   out:['drwxr-xr-x  exploits/','-rw-------  wallet.dat','-rwxr-xr-x  botnet.sh']},
  {c:'cd /root/exploits',                            m:1,   out:['{n} exploits prontos pra uso']},
  {c:'ping -t 8.8.8.8',                              m:1.5, out:['Resposta de 8.8.8.8: bytes=32 tempo={n}ms TTL=117','Resposta de 8.8.8.8: bytes=32 tempo={n}ms TTL=117','rota até o DNS do Google mapeada']},
  {c:'sudo su -',                                    m:1.5, out:['[sudo] senha aceita','agora você é root de verdade']},
  {c:'cat /etc/passwd',                              m:1.5, out:['root:x:0:0:root:/root:/bin/bash','{n} usuários encontrados']},
  {c:'netstat -tulpn',                               m:1.5, out:['tcp  0.0.0.0:22  LISTEN  sshd','{n} conexões suspeitas (todas suas)']},
  {c:'ifconfig eth0 promisc',                        m:1.5, out:['modo promíscuo ativado','farejando pacotes da rede...']},
  {c:'nmap -sS 192.168.0.1',                         m:2,   out:['22/tcp  open  ssh','80/tcp  open  http','{n} portas abertas no alvo']},
  {c:'ssh root@10.0.0.66 -p 2222',                   m:2,   out:['handshake ok, chave aceita','shell remoto estabelecido em {n}ms']},
  {c:'chmod +x exploit.sh && ./exploit.sh',          m:2,   out:['[+] payload injetado','[+] shell reverso na porta {n}']},
  {c:'tail -f /var/log/auth.log',                    m:2,   out:['Failed password for admin','Accepted password for root','admin ainda usa senha "123456"']},
  {c:'tcpdump -i eth0 port 443 -w loot.pcap',        m:2.5, out:['{n} pacotes capturados','tem coisa boa nesse .pcap']},
  {c:'hydra -l admin -P rockyou.txt ssh://10.0.0.1', m:3,   out:['[22][ssh] host: 10.0.0.1  login: admin  senha: senha123','brute force concluído em {n}s']},
  {c:'john --wordlist=rockyou.txt hashes.txt',       m:3,   out:['{n} hashes quebrados','as senhas eram todas "123456"']},
  {c:'sqlmap -u "http://alvo.com?id=1" --dump',      m:3,   out:['[INFO] parâmetro id é injetável','{n} tabelas dumpadas']},
  {c:'aircrack-ng -w rockyou.txt captura.cap',       m:3,   out:['KEY FOUND! [ senha_do_wifi ]','wifi do vizinho: liberado']},
];
const LOG_POOL = [
  'varredura de portas concluída sem alarmes',
  'café.exe executado com sucesso',
  'baixando mais RAM... (não funciona assim)',
  'wifi dos vizinhos: comprometido',
  'antivírus desativado (era estorvo)',
  'firmware da geladeira atualizado pra minerar',
  'logs limpos. que logs?',
  'VPN tripla ativada, ping de 900ms',
  'achou uma wordlist em pt-BR. eficiência +200%',
  'o admin usava admin/admin de novo',
  'criptografia quântica? ainda não inventaram defesa',
  'backup feito. confia.',
  'energia do quarteirão oscilou. foi você.',
  'mercado negro com promoção de GPU',
];
